config/routes.rb
Veganbff::Application.routes.draw do

  resources :recipes do
    resources :ingredients
  end

  resources :events

  resources :companies

  resources :products

  match 'auth/:provider/callback' => 'authentications#create'

  root :to => "recipes#index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :authentications

  
  mount Monologue::Engine, at: '/blog'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

  def provider_name
    if provider == 'open_id'
      "OpenID"
    else
      provider.titleize
    end
  end	
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :address, :city, :held_on, :name, :notes, :state, :zip
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :measurement, :name, :quantity, :recipe_id, :notes

  belongs_to :recipe
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :company_id, :name

  belongs_to :company
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name

  has_many :ingredients, :dependent => :delete_all
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications	
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def apply_omniauth(omniauth)
    self.email = omniauth['user_info']['email'] if email.blank?
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  def index
    @events = Event.all
    @events_by_date = @events.group_by(&:date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < InheritedResources::Base

  before_filter :set_recipe
  before_filter :find_ingredient, :only => [:show, :edit, :update, :destroy]

  def new
    @ingredient = @recipe.ingredients.build
  end

  def create
    @ingredient = @recipe.ingredients.build(params[:ingredient])

    if @ingredient.save
      flash[:notice] = 'Ingredient has been added.'
      redirect_to [@recipe]
    else
      flash[:alert] = 'Ingredient was not added.'
      render :action => "new"
    end
  end

  def show

  end

  def edit

  end

  def update
    if @ingredient.update_attributes(params[:ingredient])
      flash[:notice] = "Ingredient has been updated."
      redirect_to [@recipe]
    else
      flash[:alert] = "Ingredient has not been updated."
      render :action => "edit"
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    def find_ingredient
      @ingredient = @recipe.ingredients.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base 
end

app/controllers/recipes_controller.rb
class RecipesController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/calender_helper.rb
module CalenderHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/ingredients/_form.html.erb
<%= simple_form_for [@recipe, @ingredient], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.collection_select :recipe_id, Recipe.all, :id, :name %>
  <%= f.input :name %>
  <%= f.input :quantity %>
  <%= f.input :measurement %>
  <%= f.input :notes %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recipes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:recipe_id) %></th>
      <th><%= model_class.human_attribute_name(:measurement) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= link_to ingredient.id, recipe_ingredients_path(ingredient) %></td>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.recipe_id %></td>
        <td><%= ingredient.quantity %></td>
        <td><%= ingredient.measurement %></td>
        <td><%=l ingredient.created_at %></td>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_recipe_ingredient_path,
            :class => 'btn btn-primary' %>

app/views/ingredients/new.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @ingredient.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:recipe_id) %>:</strong></dt>
  <dd><%= @ingredient.recipe.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:measurement) %>:</strong></dt>
  <dd><%= @ingredient.measurement %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @ingredient.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @ingredient.notes %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              recipes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recipe_ingredient_path(@recipe, @ingredient), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recipe_ingredient_path(@recipe, @ingredient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>